CREATE DATABASE FINAL_ASSIGNMENT_JAVA3_DUNGNA29;
GO
USE FINAL_ASSIGNMENT_JAVA3_DUNGNA29;
GO

DROP TABLE IF EXISTS dongsanpham;
CREATE TABLE dongsanpham(
Id INT PRIMARY KEY IDENTITY,
MaDongSanPham NVARCHAR(100) UNIQUE DEFAULT NULL,
TenDongSanPham NVARCHAR(100) DEFAULT NULL,
WebsiteDongSanPham NVARCHAR(200) DEFAULT NULL
);
DROP TABLE IF EXISTS nhanvien;
CREATE TABLE nhanvien(
Id INT PRIMARY KEY IDENTITY,
MaNhanVien NVARCHAR(100) UNIQUE DEFAULT NULL,
TenHoNV NVARCHAR(100) DEFAULT NULL,
TenDemNV NVARCHAR(100) DEFAULT NULL,
TenNV NVARCHAR(100) DEFAULT NULL,
GioiTinh NVARCHAR(100) DEFAULT NULL,
NgaySinh Date DEFAULT NULL,
IdChucVu INT NOT NULL,
);
DROP TABLE IF EXISTS chucvu;
CREATE TABLE chucvu(
Id  INT PRIMARY KEY IDENTITY,
MaChucVu NVARCHAR(100) UNIQUE DEFAULT NULL,
TenChucVu NVARCHAR(100) DEFAULT NULL
);
DROP TABLE IF EXISTS sanpham;
CREATE TABLE sanpham(
IdSanPham INT PRIMARY KEY IDENTITY,
MaSanPHam NVARCHAR(100) UNIQUE DEFAULT NULL,
TenSP  NVARCHAR(100) DEFAULT NULL,
NamBaoHanh NUMERIC(4),
TrongLuongSP FLOAT DEFAULT NULL,
MoTaSP NVARCHAR(100) DEFAULT NULL,
SoLuongSanPhamTon INT DEFAULT NULL,
GiaNhapSP DECIMAL(20,0) DEFAULT NULL,
GiaBanSP DECIMAL(20,0) DEFAULT NULL,
IdDongSanPham INT NOT NULL
);
DROP TABLE IF EXISTS hoadon;
CREATE TABLE hoadon(
IdHoaDon INT PRIMARY KEY IDENTITY,
MaHoaDon NVARCHAR(100) UNIQUE DEFAULT NULL,
NgayMuaSP DATE DEFAULT NULL,
NgayTaoHoaDon DATE DEFAULT NULL,
NgayShipHang DATE DEFAULT NULL,
TinhTrangHoaDon  BIT DEFAULT NULL,
IdKhachHang INT NOT NULL,
IdNhanVien INT  NOT NULL
);
CREATE TABLE hoadonchitiet(
IdHoaDon INT NOT NULL,
IdSanPham INT NOT NULL ,
SoLuongDatHang INT DEFAULT NULL,
Gia1SanPham DECIMAL(20,0) DEFAULT NULL,
STTHoaDon INT DEFAULT NULL,
PRIMARY KEY(IdHoaDon,IdSanPham),
CONSTRAINT FK1 FOREIGN KEY(IdHoaDon)REFERENCES hoadon(IdHoaDon),
CONSTRAINT FK2 FOREIGN KEY(IdSanPham) REFERENCES sanpham(IdSanPham)
);

ALTER TABLE nhanvien
ADD CONSTRAINT FK_NhanVienChucDanh
FOREIGN KEY(IdChucVu) REFERENCES chucvu(IdChucVu);

ALTER TABLE nhanvien
ADD CONSTRAINT FK_NhanVienCuaHang
FOREIGN KEY(IdCuaHang) REFERENCES cuahang_fpt(IdCuaHang);

ALTER TABLE nhanvien
 ADD CONSTRAINT FK_GuiBaoCaoNhanVien
FOREIGN KEY(IdGuiBaoCao) REFERENCES nhanvien(IdNhanVien);

ALTER TABLE hoadon
ADD CONSTRAINT FK_HoaDonKhachHang
FOREIGN KEY(IdKhachHang) REFERENCES khachhang(IdKhachHang);

ALTER TABLE hoadon
ADD CONSTRAINT FK_HoaDonNhanVien
FOREIGN KEY(IdNhanVien) REFERENCES nhanvien(IdNhanVien);

ALTER TABLE sanpham
ADD CONSTRAINT FK_SanPhamDongSanPham
FOREIGN KEY(IdDongSanPham) REFERENCES dongsanpham(IdDongSanPham);